### ISSUE TITLE
[REFACTOR] Limit number of size variables

### ISSUE THREAD

**Issue by mayashavin** [DivanteLtd/storefront-ui#686]
There are too many sizes/font sizes, we need to unite them and limit the amount of variables used across the library.  One option is follow Fibonnaci design patterns to generate sizes
https://www.techniqueprint.co.uk/the-fibonacci-sequence-in-design/

**Comment by mayashavin** [comment]
Suggested from @pspaczek 
```
$font-size-extra-small: 0.75rem !default;
$font-size-small: 0.875rem !default;
$font-size-regular: 1rem !default;
$font-size-big: 1.125rem !default;
$font-size-extra-big: 1.5rem !default;
```

**Comment by pspaczek** [comment]
@mayashavin in new design we have new font-sizes, I included our _typography.scss, whad did you think?
``` scss
@import "../helpers";
:root {
  // font-family
  --font-family-primary: "Roboto", serif;
  --font-family-secondary: "Raleway", sans-serif;
  // font-weight
  --font-light: 300;
  --font-normal: 400;
  --font-medium: 500;
  --font-semibold: 600;
  --font-bold: 700;
  --font-extra-bold: 800;
  --font-black: 900;
  // font-size
  --font-2xs: 0.625rem; //10px
  --font-xs: 0.75rem; //12px
  --font-sm: 0.875rem; //14px
  --font-base: 1rem; //16px
  --font-lg: 1.125rem; //18px
  --font-xl: 1.5rem; //24px
  // heading font-size
  --h1-font-size: 1.625rem; //26px
  --h2-font-size: 1.375rem; //22px
  --h3-font-size: 1.125rem; //18px
  --h4-font-size: 0.875rem; //14px
  --h5-font-size: 0.75rem; //12px
  --h6-font-size: 0.75rem; //12px
  @include for-desktop {
    --h1-font-size: 2.625rem; //42px
    --h2-font-size: 2.625rem; //42px
    --h3-font-size: 1.75rem; //28px
    --h4-font-size: 1.125rem; //18px
    --h5-font-size: 0.875rem; //14px
    --h6-font-size: 0.875rem; //14px
  }
}
```
