### ISSUE TITLE
[REFACTOR] Adjust CSS variable to 'Default values' pattern

### ISSUE THREAD

**Issue by pspaczek** [DivanteLtd/storefront-ui#733]
Acceptance Criteria
- walid components styles in storybook
- use 'default values' pattern for CSS variables [inspiration](https://css-tricks.com/patterns-for-practical-css-custom-properties-use/#article-header-id-2)
``` css
.sf-button {
  margin: var(--button-margin);
  padding: var(--button-padding, 1.5rem 2.5rem);
}
```
- update docs for 'default values' pattern
- update auto generation dosc scripts
- #445 limit number of CSS vars to certain properties
