### ISSUE TITLE
[REFACTOR] Remove calc from SfChevron

### ISSUE THREAD

**Issue by pspaczek** [DivanteLtd/storefront-ui#752]
!copy .scss file from #744
Please remove 'calc' from SfChevron.scss it's a bad performance pattern
``` scss
.sf-chevron__bar {
  // line 9 in SfChevron.scss
  top: calc(calc(var(--chevron-size, 1.25rem) / 2) - calc(calc(calc(var(--chevron-size, 1.25rem) / 2) / 5) / 2));
}
```
SfChevron base on this [codepen](https://codepen.io/mattbraun/pen/EywBJR)
