### ISSUE TITLE
[REFACTOR] ORGANISMS adjust Storefrnt UI design system

### ISSUE THREAD

**Issue by pspaczek** [DivanteLtd/storefront-ui#806]
rewrite organisms CSS for a new design system http://bit.ly/storefront-ui-design-system

Workflow:
1. create a branch from `refactor/design-system`
2. create PR with your changes

Notes: 
1. **don't** touch components props API
2. note on PR all changes in component CSS modifiers API
3. in components styles you should use **always** css variables, don't use hardcode values for spacers, colour's, font's etc.
4. spacers should be align to 8px grid like on Google Matrial
5. refactor workflow
- move css to outide file
- set style for base component
a. set font
b. set spacers
c. set color's
d. set others property
- create modifiers
- test it 🙏
- push it
6. we shouldn't use different element font size in component, it should be the same
``` scss
// *don't
.sf-button{
font-size: --body-font-size-regular;
  @include for-desktop {
    font-size: --body-font-size-extra-big;
  }
}
```
7.  scss filer structure
``` scss
@import "../../helpers";
.sf-button{
  width: 
  height:
  padding:
  @include for-desktop {
  --button-padding:
  }
  &--modifier {
    --button-padding:
   }
}
```
Scope of work:
*please assigne you to component 
- [x] Accordion @aniamusial 
- [ ] Banner Grid @pspaczek 
- [x] Bottom Navigation @martaradziszewska 
- [ ] Carouse @justyna-13 
- [ ] Collected Product @aniamusial 
- [ ] Content Pages @adampawlinski 
- [ ] Footer @justyna-13 
- [ ] Gruped Product @aniamusial 
- [x] Header @aniamusial 
- [ ] Hero @adampawlinski 
- [ ] List @adampawlinski 
- [x] Mega Menu @martaradziszewska 
- [x] Product Card @martaradziszewska 
- [x] Product Card Horizontal @martaradziszewska 
- [x] Sidebar @martaradziszewska 
- [ ] StoreLocator @aniamusial 
- [x] Table @aniamusial 
- [ ] Tabs @justyna-13 
- [ ] Top Bar @justyna-13
